---
title: "Day4Comp108102023"
format: html
editor: visual
---

## Create vectors

```{r}
#use concatnate to create vectors in R [c()]
rain <- c(3,5,10.1,6)

rain_scaled <- 5 * rain

```

## Create matrices

```{r}
my_values <- seq(from=1,to=10)
```

```{r}
my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = 2)
```

use the function rm() to delete a mistake, ex: rm(my_matrix) to delete it from the environment

```{r}
my_matrix2 <- matrix(data = my_values, nrow = 3, ncol = 4, byrow = TRUE)
```

```{r}
matrixA <- matrix(data = seq(from = 2, to = 5, length = 10),
                  nrow = 2,
                  ncol = 5,
                  byrow = TRUE)
```

## Matrix Math

```{r}
my_matrix + matrixA
```

## Matrix Multiplication

```{r}
cats <- matrix(data = c(0,4,3,1),
               nrow = 2, ncol = 2, byrow = TRUE)
dogs <- matrix(data = c(6,-3,0,2),
               nrow = 2, ncol = 2, byrow = TRUE)
```

```{r}
dogs %*% cats #for the dot product
```

## Leslie Matrix Example

```{r}
insect_leslie <- matrix(data = c(0,0,600,0.2,0,0,0,0.08,0),
                        nrow = 3, ncol = 3, byrow = TRUE)
insect_y0 <- c(12000, 700, 500)
```

Find the population structure for each life stage at t = 1 year:

```{r}
insect_y1 <- insect_leslie %*% insect_y0
insect_y1
#we are multiplying a matrix by a vector, but since they match in col/row it treats it as a matrix with a single column and three rows
```

Find the population structure at t = 2 years:

```{r}
insect_y2 <- insect_leslie %*% insect_y1
insect_y2
```
